### ISSUE TITLE
ValueError in get_feature_clusters

### ISSUE THREAD

**Issue by MislavSag** [hudson-and-thames/mlfinlab#405]
**Describe the bug**
I am trying to apply `get_feature_clusters` function on my feature set. The function returns:
`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`

I checked for Nan and Inf values and I don't have it in my data frame.

**To Reproduce**
```
import pandas as pd
import numpy as np
import mlfinlab as ml

url = 'https://raw.githubusercontent.com/MislavSag/trademl/master/trademl/modeling/random_forest/X_TEST.csv'
X_TEST = pd.read_csv(url, sep=',')
feat_subs = ml.clustering.get_feature_clusters(
    X_TEST, dependence_metric='information_variation',
    distance_metric='angular', linkage_method='singular', n_clusters=4)
```

**Expected behavior**
Return clusters of features.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser 
 - Version

**Comment by PanPip** [comment]
@MislavSag thank you for reporting this issue.

It is also described in Issue #341 and will be fixed in the soon future.

**Comment by PanPip** [comment]
This issue was caused by precision errors in the ONC module (the main diagonal of the correlation matrix was slightly higher than 1, so the distance matrix couldn't be calculated).

This issue is now fixed in PR #412

**Comment by MislavSag** [comment]
@PanPip Should I install from github or I have to wait for new release to try the function again?

**Comment by PanPip** [comment]
@MislavSag It will be pushed to the `develop` branch at the end of the week and then soon to `master`.

To try it now you can install a local version from the `fix_issues` branch. We'll try to push it to `master` as soon as we can.

**Comment by MislavSag** [comment]
Ok, I will wait to be added to the master.

**Comment by MislavSag** [comment]
I tried to copy-paste functions from develop branch and execute, but still get the same error?

**Comment by PanPip** [comment]
@MislavSag Thanks.

It's again due to numerical errors, but now for values not on the main diagonal of the correlation matrix. I'll fix it.

In your dataset these pairs of values are perfectly correlated:
`RSI30 - CMO30`
`RSI480 - CMO480`
`RSI2400 - CMO2400`

You can remove them and the function will work without any problems.

**Comment by PanPip** [comment]
A quick fix, for now, would be to replace line **62** in `mlfinlab/clustering/onc.py`

from
`np.fill_diagonal(corr_mat.values, 1)`

to
`corr_mat[corr_mat > 1] = 1`

**Comment by PanPip** [comment]
Fun fact, Pandas correlation function output can be > 1. I'll report this issue.

**Comment by PanPip** [comment]
This Issue is closed in PR #421.

@MislavSag I've tested it specifically on your dataset. Just change `linkage_method='singular'` to `linkage_method='single'`

**Comment by MislavSag** [comment]
I removed highly correlated features from my X. I have also change the line 62 as you recommenden. Folloeing code works:

```
feat_subs = get_feature_clusters(data,
                                 dependence_metric='information_variation',
                                 distance_metric='angular',
                                 linkage_method='single',
                                 n_clusters=4)
```

but the code (from research notebook): 
```
clusters = ml.clustering.get_feature_clusters(
    data,
    dependence_metric='linear',
    distance_metric=None,
    linkage_method=None, 
    n_clusters=None)
```
still returns an error:
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by PanPip** [comment]
@MislavSag 

Just tested using the code from `develop` branch on the `Cluster_Feature_Importance.ipynb`notebook. Had no issues. Are you referring to this notebook?

![picture](https://user-images.githubusercontent.com/16906989/86743062-e4f22f00-c038-11ea-9675-90e06cd28a85.png)

**Comment by MislavSag** [comment]
Have you tried with my dataset?

**Comment by PanPip** [comment]
@MislavSag 

Yes. Just remove the first column as those are dates and not numbers.

![picture](https://user-images.githubusercontent.com/16906989/86776351-6dcc9300-c058-11ea-947b-05ed7196db17.png)
